---
- name: Install Apache and PHP
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-curl
      - php-json
      - php-mbstring
      - libapache2-mod-php
    state: present

- name: Enable Apache modules
  apache2_module:
    name: rewrite
    state: present
  notify: Restart Apache

- name: Configure DirectoryIndex
  lineinfile:
    path: /etc/apache2/mods-enabled/dir.conf
    regexp: '^(\s*)DirectoryIndex.*'
    line: '\1DirectoryIndex login.php index.php index.html index.cgi index.pl index.xhtml index.htm'
    backrefs: yes
  notify: Restart Apache

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
